### ISSUE TITLE
Cannot read property 'width' of undefined

### ISSUE THREAD

**Issue by binzailani3136** [stoffern/react-native-optimized-flatlist#1]
You did a good job.
I've tried your library on my code and it still looks a little weird sometimes when scrolling up and down.
If I suddenly scroll up, it doesn't displays upper list items and if i try scrolling gesture rapidly many times, it shows me such error.
Please have a look.
![screen shot 2017-05-08 at 10 50 48 am](https://cloud.githubusercontent.com/assets/20284956/25788557/91a22b98-33dc-11e7-9eaa-c4313c7a689c.png)

**Comment by stoffern** [comment]
hm, looks like the onLayout function fails to measure the item size.
Can you make a reproduction repo of it?

**Comment by stoffern** [comment]
@binzailani3136 did you solve this issue?

**Comment by pvsousalima** [comment]
I am having the same error here!

**Comment by binzailani3136** [comment]
I wasn't able to solve this issue.

**Comment by satish25** [comment]
Even I'm facing the same issue

**Comment by DavidFP** [comment]
> I am having the same error here!

Me too
