### ISSUE TITLE
FlatlistRef.ScrollToIndex is not a function

### ISSUE THREAD

**Issue by NikiTsv** [stoffern/react-native-optimized-flatlist#29]
I am not able to use scrollToIndex.
Is that intended?
``` ref={(ref) => { this.flatListRef = ref; }}```

**Comment by st0ffern** [comment]
It should work, but call the function directly instead of ref.

**Comment by Sangrene** [comment]
Hey @stoffern , how do you call this function "directly" without a ref to the proper component then ?

**Comment by wasedaigo** [comment]
yeah , what is the usage?

**Comment by yannoudou** [comment]
i think a find a way to deal with that issue.

1.   pass that **ref={(ref) => { this.flatListRef = ref; }}** to  **OptimizedFlatList Component** 

2.   create in  **OptimizedFlatList** a  **scrollToIndex function** and bind it in the constructor: like
`this.scrollToIndex=this.scrollToIndex.bind(this)`.

3.    your **scrollToIndex function** could look like:
`scrollToIndex(){
// what ever you want to achieve
}`
4.   you can call now **`this.flatListRef.scrollToIndex(index)`** and the **scrollToIndex function** you have created in OptimizedFlatList, will trigger
