### ISSUE TITLE
Incompatible with RN 55+ 

### ISSUE THREAD

**Issue by mmckinley8** [stoffern/react-native-optimized-flatlist#30]
Seeing this error after simply running `yarn add react-native-optimized-flatlist`

![simulator screen shot - iphone 6 - 2018-05-09 at 09 55 56](https://user-images.githubusercontent.com/11301364/39822042-3d95dd16-536f-11e8-895e-f166253d9f32.png)

**Comment by st0ffern** [comment]
Well this has nothing to do with `react-native-optimized-flatlist`
Have you read the error? It states that:
/Users/mikemckinley/Development/movespring/mobile/node_modules/native-base/dist/src/basic/SwipeRow.js does not exsist

tried removing node_modules and reinstall them?
