### ISSUE TITLE
Scroll functions

### ISSUE THREAD

**Issue by mahdikhosravi** [stoffern/react-native-optimized-flatlist#35]
Hi,
The last release does not have scroll functions. When is the deadline for next release?

**Comment by st0ffern** [comment]
scrolling works. add more data!

**Comment by mahdikhosravi** [comment]
The version in npmjs is 1.0.4 which did not have functions such as scrollToIndex. After I opened this topic, I forked the repo and release that to the npmjs website. So now everything works for me now. But I ratter to use package with your name, not mine.
