### ISSUE TITLE
Removing rendered item causes index error

### ISSUE THREAD

**Issue by atpunk** [stoffern/react-native-optimized-flatlist#5]
"react": "16.0.0-alpha.3",
"react-native": "0.44.0",
"react-native-optimized-flatlist": "^1.0.1"

I am receiving the following error when I delete an item from the flatlist.

![image](https://user-images.githubusercontent.com/6874950/27805401-44495716-5fe9-11e7-8867-0aefec04f7a2.png)

**Comment by Shinichi52** [comment]
i see perfomance verry good. but i has same this issue and https://github.com/stoffern/react-native-optimized-flatlist/issues/1

**Comment by stoffern** [comment]
This should be fixed now 😉
