### ISSUE TITLE
Proptypes.element undefined

### ISSUE THREAD

**Issue by elliscwc** [stoffern/react-native-optimized-flatlist#9]
![proptype](https://user-images.githubusercontent.com/29953232/31448512-33ca6320-aed7-11e7-8a4a-5d2275dc214e.png)

@stoffern could you look at this error? I'm using RN 0.49

**Comment by stoffern** [comment]
it is because proptypes is moved out of react native. will fix it soon.

**Comment by elliscwc** [comment]
@stoffern is there an update for this?

**Comment by stoffern** [comment]
b7afeff5e6201f3d60931a07f97bb5c424356a5a
